local _, addon = ...

local GuildRosterData = {
    {
        name = "Shadowstrike",
        rank = "Member",
        rankIndex = 5,
        level = 30,
        class = "Rogue",
        zone = "Undercity",
        note = "",
        officernote = "",
        online = true,
        status = 1, -- Away
        classFileName = "ROGUE",
        achievementPoints = 1500,
        achievementRank = 3,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Whisperstorm",
        rank = "Officer",
        rankIndex = 2,
        level = 45,
        class = "Mage",
        zone = "Stormwind City",
        note = "",
        officernote = "",
        online = true,
        status = 0, -- Available
        classFileName = "MAGE",
        achievementPoints = 2500,
        achievementRank = 5,
        isMobile = false,
        isSoREligible = true,
        standingID = 2,
    },
    {
        name = "Ravenheart",
        rank = "Member",
        rankIndex = 5,
        level = 25,
        class = "Rogue",
        zone = "Undercity",
        note = "",
        officernote = "",
        online = false,
        status = 2, -- Busy
        classFileName = "ROGUE",
        achievementPoints = 1200,
        achievementRank = 2,
        isMobile = true,
        isSoREligible = false,
        standingID = 3,
    },
    {
        name = "Frostwhisper",
        rank = "Member",
        rankIndex = 5,
        level = 60,
        class = "Warlock",
        zone = "Thunder Bluff",
        note = "",
        officernote = "",
        online = true,
        status = 1, -- Away
        classFileName = "WARLOCK",
        achievementPoints = 3200,
        achievementRank = 6,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Moonstrike",
        rank = "Member",
        rankIndex = 5,
        level = 55,
        class = "Druid",
        zone = "Orgrimmar",
        note = "",
        officernote = "",
        online = false,
        status = 2, -- Busy
        classFileName = "DRUID",
        achievementPoints = 2800,
        achievementRank = 4,
        isMobile = true,
        isSoREligible = false,
        standingID = 2,
    },
    {
        name = "Firestorm",
        rank = "Officer",
        rankIndex = 2,
        level = 70,
        class = "Paladin",
        zone = "Stormwind City",
        note = "",
        officernote = "",
        online = true,
        status = 0, -- Available
        classFileName = "PALADIN",
        achievementPoints = 4000,
        achievementRank = 7,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Silvermoon",
        rank = "Member",
        rankIndex = 5,
        level = 40,
        class = "Hunter",
        zone = "Thunder Bluff",
        note = "",
        officernote = "",
        online = true,
        status = 1, -- Away
        classFileName = "HUNTER",
        achievementPoints = 1800,
        achievementRank = 2,
        isMobile = false,
        isSoREligible = true,
        standingID = 3,
    },
    {
        name = "Mysticshroud",
        rank = "Officer",
        rankIndex = 2,
        level = 50,
        class = "Priest",
        zone = "Darnassus",
        note = "",
        officernote = "",
        online = false,
        status = 2, -- Busy
        classFileName = "PRIEST",
        achievementPoints = 2200,
        achievementRank = 3,
        isMobile = true,
        isSoREligible = false,
        standingID = 2,
    },
    {
        name = "Thunderstrike",
        rank = "Member",
        rankIndex = 5,
        level = 65,
        class = "Shaman",
        zone = "Orgrimmar",
        note = "",
        officernote = "",
        online = true,
        status = 0, -- Available
        classFileName = "SHAMAN",
        achievementPoints = 3500,
        achievementRank = 6,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Moroc",
        rank = "Humongous",
        rankIndex = 1,
        level = 80,
        class = "Warrior",
        zone = "The Ringing Deeps",
        note = "",
        officernote = "",
        online = true,
        status = 2, -- Away
        classFileName = "WARRIOR",
        achievementPoints = 1500,
        achievementRank = 3,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Ebonheart",
        rank = "Officer",
        rankIndex = 2,
        level = 45,
        class = "Mage",
        zone = "Thunder Bluff",
        note = "",
        officernote = "",
        online = true,
        status = 0, -- Available
        classFileName = "MAGE",
        achievementPoints = 2500,
        achievementRank = 5,
        isMobile = false,
        isSoREligible = true,
        standingID = 2,
    },
    {
        name = "Nightstrike",
        rank = "Member",
        rankIndex = 5,
        level = 25,
        class = "Rogue",
        zone = "Orgrimmar",
        note = "",
        officernote = "",
        online = true,
        status = 2, -- Busy
        classFileName = "ROGUE",
        achievementPoints = 1200,
        achievementRank = 2,
        isMobile = false,
        isSoREligible = false,
        standingID = 3,
    },
    {
        name = "Shadowcaster",
        rank = "Member",
        rankIndex = 5,
        level = 60,
        class = "Warlock",
        zone = "Stormwind City",
        note = "",
        officernote = "",
        online = true,
        status = 1, -- Away
        classFileName = "WARLOCK",
        achievementPoints = 3800,
        achievementRank = 6,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Stormbringer",
        rank = "Member",
        rankIndex = 5,
        level = 55,
        class = "Druid",
        zone = "Orgrimmar",
        note = "",
        officernote = "",
        online = false,
        status = 2, -- Busy
        classFileName = "DRUID",
        achievementPoints = 2800,
        achievementRank = 4,
        isMobile = true,
        isSoREligible = false,
        standingID = 2,
    },
    {
        name = "Stargazer",
        rank = "Member",
        rankIndex = 5,
        level = 40,
        class = "Hunter",
        zone = "Thunder Bluff",
        note = "",
        officernote = "",
        online = true,
        status = 1, -- Away
        classFileName = "HUNTER",
        achievementPoints = 1800,
        achievementRank = 2,
        isMobile = false,
        isSoREligible = true,
        standingID = 3,
    },
    {
        name = "Stormcaller",
        rank = "Member",
        rankIndex = 5,
        level = 65,
        class = "Shaman",
        zone = "Orgrimmar",
        note = "",
        officernote = "",
        online = true,
        status = 0, -- Available
        classFileName = "SHAMAN",
        achievementPoints = 3500,
        achievementRank = 6,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Valiant",
        rank = "Member",
        rankIndex = 5,
        level = 30,
        class = "Warrior",
        zone = "Undercity",
        note = "",
        officernote = "",
        online = true,
        status = 1, -- Away
        classFileName = "WARRIOR",
        achievementPoints = 1500,
        achievementRank = 3,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Frostwind",
        rank = "Officer",
        rankIndex = 2,
        level = 45,
        class = "Mage",
        zone = "Thunder Bluff",
        note = "",
        officernote = "",
        online = true,
        status = 0, -- Available
        classFileName = "MAGE",
        achievementPoints = 2500,
        achievementRank = 5,
        isMobile = false,
        isSoREligible = true,
        standingID = 2,
    },
    {
        name = "Nightblade",
        rank = "Member",
        rankIndex = 5,
        level = 25,
        class = "Rogue",
        zone = "Orgrimmar",
        note = "",
        officernote = "",
        online = false,
        status = 2, -- Busy
        classFileName = "ROGUE",
        achievementPoints = 1200,
        achievementRank = 2,
        isMobile = true,
        isSoREligible = false,
        standingID = 3,
    },
    {
        name = "Dreadweaver",
        rank = "Member",
        rankIndex = 5,
        level = 60,
        class = "Warlock",
        zone = "Stormwind City",
        note = "",
        officernote = "",
        online = true,
        status = 1, -- Away
        classFileName = "WARLOCK",
        achievementPoints = 3800,
        achievementRank = 6,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Gloomshadow",
        rank = "Member",
        rankIndex = 5,
        level = 55,
        class = "Druid",
        zone = "Orgrimmar",
        note = "",
        officernote = "",
        online = false,
        status = 2, -- Busy
        classFileName = "DRUID",
        achievementPoints = 2800,
        achievementRank = 4,
        isMobile = true,
        isSoREligible = false,
        standingID = 2,
    },
    {
        name = "Lightbringer",
        rank = "Officer",
        rankIndex = 2,
        level = 70,
        class = "Paladin",
        zone = "Stormwind City",
        note = "",
        officernote = "",
        online = true,
        status = 0, -- Available
        classFileName = "PALADIN",
        achievementPoints = 4000,
        achievementRank = 7,
        isMobile = false,
        isSoREligible = true,
        standingID = 1,
    },
    {
        name = "Moonshadow",
        rank = "Officer",
        rankIndex = 2,
        level = 50,
        class = "Priest",
        zone = "Darnassus",
        note = "",
        officernote = "",
        online = false,
        status = 2, -- Busy
        classFileName = "PRIEST",
        achievementPoints = 2200,
        achievementRank = 3,
        isMobile = true,
        isSoREligible = false,
        standingID = 2,
    },
    {
        name = "Firesong",
        rank = "Officer",
        rankIndex = 2,
        level = 45,
        class = "Mage",
        zone = "Thunder Bluff",
        note = "",
        officernote = "",
        online = true,
        status = 0, -- Available
        classFileName = "MAGE",
        achievementPoints = 2500,
        achievementRank = 5,
        isMobile = false,
        isSoREligible = true,
        standingID = 2,
    },
    {
        name = "Shadowblade",
        rank = "Member",
        rankIndex = 5,
        level = 25,
        class = "Rogue",
        zone = "Orgrimmar",
        note = "",
        officernote = "",
        online = false,
        status = 2, -- Busy
        classFileName = "ROGUE",
        achievementPoints = 1200,
        achievementRank = 2,
        isMobile = true,
        isSoREligible = false,
        standingID = 3,
    },
}

do
    local Guild = addon:GetObject("Guild", true) or {}

    Guild.GetNumGuildMembers = function()
        local onlineMembers = 0
        for _, info in ipairs(GuildRosterData) do
            if info.online then
                onlineMembers = onlineMembers + 1
            end
        end
        return #GuildRosterData, onlineMembers
    end

    Guild.GetGuildRosterInfo = function(index)
        local info = GuildRosterData[index]
        return info.name, info.rank, info.rankIndex, info.level, info.class, info.zone, info.note, info.officernote, info.online, info.status, info.classFileName, info.achievementPoints, info.achievementRank, info.isMobile, info.isSoREligible, info.standingID
    end
end

do
    local FriendInfo = {
        [1] = {
            connected = GuildRosterData[11].online,
            name = GuildRosterData[11].name,
            className = GuildRosterData[11].class,
            area = GuildRosterData[11].zone,
            notes = GuildRosterData[11].note,
            guid = "Player-2808-4MZ129JIP5",
            level = GuildRosterData[11].level,
            dnd = (GuildRosterData[11].status == 2),
            afk = (GuildRosterData[11].status == 1),
            rafLinkType = nil,
            mobile = GuildRosterData[11].isMobile,
        },
        [2] = {
            connected = GuildRosterData[12].online,
            name = GuildRosterData[12].name,
            className = GuildRosterData[12].class,
            area = GuildRosterData[12].zone,
            notes = GuildRosterData[12].note,
            guid = "Player-5831-MFNHT71W2F",
            level = GuildRosterData[12].level,
            dnd = (GuildRosterData[12].status == 2),
            afk = (GuildRosterData[12].status == 1),
            rafLinkType = nil,
            mobile = GuildRosterData[12].isMobile,
        },
        [3] = {
            connected = GuildRosterData[13].online,
            name = GuildRosterData[13].name,
            className = GuildRosterData[13].class,
            area = GuildRosterData[13].zone,
            notes = GuildRosterData[13].note,
            guid = "Player-3603-OE0LPE3ZUA",
            level = GuildRosterData[13].level,
            dnd = (GuildRosterData[13].status == 2),
            afk = (GuildRosterData[13].status == 1),
            rafLinkType = nil,
            mobile = GuildRosterData[13].isMobile,
        },
        [4] = {
            connected = GuildRosterData[15].online,
            name = GuildRosterData[15].name,
            className = GuildRosterData[15].class,
            area = GuildRosterData[15].zone,
            notes = GuildRosterData[15].note,
            guid = "Player-1251-O6K752XNCU",
            level = GuildRosterData[15].level,
            dnd = (GuildRosterData[15].status == 2),
            afk = (GuildRosterData[15].status == 1),
            rafLinkType = nil,
            mobile = GuildRosterData[15].isMobile,
        },
        [5] = {
            connected = GuildRosterData[20].online,
            name = GuildRosterData[20].name,
            className = GuildRosterData[20].class,
            area = GuildRosterData[20].zone,
            notes = GuildRosterData[20].note,
            guid = "Player-1528-1LWJNYNAUB",
            level = GuildRosterData[20].level,
            dnd = (GuildRosterData[20].status == 2),
            afk = (GuildRosterData[20].status == 1),
            rafLinkType = nil,
            mobile = GuildRosterData[20].isMobile,
        },
        [6] = {
            connected = GuildRosterData[22].online,
            name = GuildRosterData[22].name,
            className = GuildRosterData[22].class,
            area = GuildRosterData[22].zone,
            notes = GuildRosterData[22].note,
            guid = "Player-7932-YBEFCJWJIE",
            level = GuildRosterData[22].level,
            dnd = (GuildRosterData[22].status == 2),
            afk = (GuildRosterData[22].status == 1),
            rafLinkType = nil,
            mobile = GuildRosterData[22].isMobile,
        },
        [7] = {
            connected = GuildRosterData[25].online,
            name = GuildRosterData[25].name,
            className = GuildRosterData[25].class,
            area = GuildRosterData[25].zone,
            notes = GuildRosterData[25].note,
            guid = "Player-2115-KDMS08HYO4",
            level = GuildRosterData[25].level,
            dnd = (GuildRosterData[25].status == 2),
            afk = (GuildRosterData[25].status == 1),
            rafLinkType = nil,
            mobile = GuildRosterData[25].isMobile,
        }
    }

    local BNetGameAccountInfo = {
        [1] = {
            gameAccountID = 1,
            clientProgram = "WoW",
            isOnline = GuildRosterData[1].online,
            isGameBusy = GuildRosterData[1].status == 2, -- Busy
            isGameAFK = GuildRosterData[1].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[1].name,
            realmName = "Aegwynn",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[1].faction,
            raceName = GuildRosterData[1].race,
            className = GuildRosterData[1].class,
            areaName = GuildRosterData[1].zone,
            characterLevel = GuildRosterData[1].level,
            richPresence = GuildRosterData[1].zone .. " - Aegwynn",
            playerGuid = "123456789",
            isWowMobile = GuildRosterData[1].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        },
        [2] = {
            gameAccountID = 2,
            clientProgram = "WoW",
            isOnline = GuildRosterData[2].online,
            isGameBusy = GuildRosterData[2].status == 2, -- Busy
            isGameAFK = GuildRosterData[2].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[2].name,
            realmName = "Argent Dawn",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[2].faction,
            raceName = GuildRosterData[2].race,
            className = GuildRosterData[2].class,
            areaName = GuildRosterData[2].zone,
            characterLevel = GuildRosterData[2].level,
            richPresence = GuildRosterData[2].zone .. " - Argent Dawn",
            playerGuid = "234567890",
            isWowMobile = GuildRosterData[2].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        },
        [3] = {
            gameAccountID = 3,
            clientProgram = "WoW",
            isOnline = GuildRosterData[3].online,
            isGameBusy = GuildRosterData[3].status == 2, -- Busy
            isGameAFK = GuildRosterData[3].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[3].name,
            realmName = "Eredar",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[3].faction,
            raceName = GuildRosterData[3].race,
            className = GuildRosterData[3].class,
            areaName = GuildRosterData[3].zone,
            characterLevel = GuildRosterData[3].level,
            richPresence = GuildRosterData[3].zone .. " - Eredar",
            playerGuid = "345678901",
            isWowMobile = GuildRosterData[3].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        },
        [4] = {
            gameAccountID = 4,
            clientProgram = "WoW",
            isOnline = GuildRosterData[4].online,
            isGameBusy = GuildRosterData[4].status == 2, -- Busy
            isGameAFK = GuildRosterData[4].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[4].name,
            realmName = "Shadowmoon",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[4].faction,
            raceName = GuildRosterData[4].race,
            className = GuildRosterData[4].class,
            areaName = GuildRosterData[4].zone,
            characterLevel = GuildRosterData[4].level,
            richPresence = GuildRosterData[4].zone .. " - Shadowmoon",
            playerGuid = "456789012",
            isWowMobile = GuildRosterData[4].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        },
        [5] = {
            gameAccountID = 5,
            clientProgram = "WoW",
            isOnline = GuildRosterData[5].online,
            isGameBusy = GuildRosterData[5].status == 2, -- Busy
            isGameAFK = GuildRosterData[5].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[5].name,
            realmName = "Twisting Nether",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[5].faction,
            raceName = GuildRosterData[5].race,
            className = GuildRosterData[5].class,
            areaName = GuildRosterData[5].zone,
            characterLevel = GuildRosterData[5].level,
            richPresence = GuildRosterData[5].zone .. " - Twisting Nether",
            playerGuid = "567890123",
            isWowMobile = GuildRosterData[5].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        },
        [6] = {
            gameAccountID = 6,
            clientProgram = "WoW",
            isOnline = GuildRosterData[6].online,
            isGameBusy = GuildRosterData[6].status == 2, -- Busy
            isGameAFK = GuildRosterData[6].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[6].name,
            realmName = "Sylvanas",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[6].faction,
            raceName = GuildRosterData[6].race,
            className = GuildRosterData[6].class,
            areaName = GuildRosterData[6].zone,
            characterLevel = GuildRosterData[6].level,
            richPresence = GuildRosterData[6].zone .. " - Sylvanas",
            playerGuid = "678901234",
            isWowMobile = GuildRosterData[6].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        },
        [7] = {
            gameAccountID = 7,
            clientProgram = "WoW",
            isOnline = GuildRosterData[7].online,
            isGameBusy = GuildRosterData[7].status == 2, -- Busy
            isGameAFK = GuildRosterData[7].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[7].name,
            realmName = "Ragnaros",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[7].faction,
            raceName = GuildRosterData[7].race,
            className = GuildRosterData[7].class,
            areaName = GuildRosterData[7].zone,
            characterLevel = GuildRosterData[7].level,
            richPresence = GuildRosterData[7].zone .. " - Ragnaros",
            playerGuid = "789012345",
            isWowMobile = GuildRosterData[7].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        },
        [8] = {
            gameAccountID = 8,
            clientProgram = "WoW",
            isOnline = GuildRosterData[8].online,
            isGameBusy = GuildRosterData[8].status == 2, -- Busy
            isGameAFK = GuildRosterData[8].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[8].name,
            realmName = "Frostmane",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[8].faction,
            raceName = GuildRosterData[8].race,
            className = GuildRosterData[8].class,
            areaName = GuildRosterData[8].zone,
            characterLevel = GuildRosterData[8].level,
            richPresence = GuildRosterData[8].zone .. " - Frostmane",
            playerGuid = "890123456",
            isWowMobile = GuildRosterData[8].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        },
        [9] = {
            gameAccountID = 9,
            clientProgram = "WoW",
            isOnline = GuildRosterData[9].online,
            isGameBusy = GuildRosterData[9].status == 2, -- Busy
            isGameAFK = GuildRosterData[9].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[9].name,
            realmName = "Outland",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[9].faction,
            raceName = GuildRosterData[9].race,
            className = GuildRosterData[9].class,
            areaName = GuildRosterData[9].zone,
            characterLevel = GuildRosterData[9].level,
            richPresence = GuildRosterData[9].zone .. " - Outland",
            playerGuid = "901234567",
            isWowMobile = GuildRosterData[9].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        },
        [10] = {
            gameAccountID = 10,
            clientProgram = "WoW",
            isOnline = GuildRosterData[10].online,
            isGameBusy = GuildRosterData[10].status == 2, -- Busy
            isGameAFK = GuildRosterData[10].status == 1,
            wowProjectID = nil,
            characterName = GuildRosterData[10].name,
            realmName = "Kazzak",
            realmDisplayName = nil,
            realmID = nil,
            factionName = GuildRosterData[10].faction,
            raceName = GuildRosterData[10].race,
            className = GuildRosterData[10].class,
            areaName = GuildRosterData[10].zone,
            characterLevel = GuildRosterData[10].level,
            richPresence = GuildRosterData[10].zone .. " - Kazzak",
            playerGuid = "012345678",
            isWowMobile = GuildRosterData[10].isMobile,
            canSummon = false,
            hasFocus = false,
            regionID = 1,
            isInCurrentRegion = true,
        }
    }

    local BNetAccountInfo = {
        {
            bnetAccountID = 1,
            accountName = "John Doe",
            gameAccountInfo = BNetGameAccountInfo[1]
        },
        {
            bnetAccountID = 2,
            accountName = "Elena Smith",
            isFavorite = true,
            gameAccountInfo = BNetGameAccountInfo[2]
        },
        {
            bnetAccountID = 3,
            accountName = "Michael Johnson",
            isFavorite = true,
            gameAccountInfo = BNetGameAccountInfo[3]
        },
        {
            bnetAccountID = 4,
            accountName = "Emily Clark",
            isFavorite = true,
            appearOffline = true,
            gameAccountInfo = BNetGameAccountInfo[4]
        },
        {
            bnetAccountID = 5,
            accountName = "David Brown",
            gameAccountInfo = BNetGameAccountInfo[5]
        },
        {
            bnetAccountID = 6,
            accountName = "Jessica Miller",
            gameAccountInfo = BNetGameAccountInfo[6]
        },
        {
            bnetAccountID = 7,
            accountName = "Christopher Wilson",
            appearOffline = true,
            gameAccountInfo = BNetGameAccountInfo[7]
        },
        {
            bnetAccountID = 8,
            accountName = "Laura Davis",
            gameAccountInfo = BNetGameAccountInfo[8]
        },
        {
            bnetAccountID = 9,
            accountName = "Daniel Martinez",
            gameAccountInfo = BNetGameAccountInfo[9]
        },
        {
            bnetAccountID = 10,
            accountName = "Andreas",
            gameAccountInfo = BNetGameAccountInfo[10]
        },
    }

    local Friends = addon:GetObject("Friends", true) or {}

     Friends.GetNumFriends = function()
        return #FriendInfo
    end

    Friends.GetNumOnlineFriends = function()
        local onlineFriends = 0
        for _, info in ipairs(FriendInfo) do
            if info.connected then
                onlineFriends = onlineFriends + 1
            end
        end
        return onlineFriends
    end

    Friends.GetFriendInfoByIndex = function(index)
        return FriendInfo[index]
    end

    Friends.BNGetNumFriends = function()
        local onlineFriends = 0
        for _, info in ipairs(BNetAccountInfo) do
            if info.gameAccountInfo.isOnline then
                onlineFriends = onlineFriends + 1
            end
        end
        return #BNetAccountInfo, onlineFriends, 0, 0
    end

    Friends.GetFriendAccountInfo = function(index)
        return BNetAccountInfo[index]
    end

    Friends.GetAccountInfoByID = function(bnetAccountID)
        for _, info in ipairs(BNetAccountInfo) do
            if info.bnetAccountID == bnetAccountID then
                return info
            end
        end
    end
end